source 'https://rubygems.org'

gem 'sinatra'
gem 'pg'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'rspec'
gem 'pry'
gem 'json'
gem 'simplecov'
gem 'shoulda-matchers'
