source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'rspec'
gem 'pry'
gem 'json'
gem 'simplecov'
gem 'fast_jsonapi'
gem 'shoulda-matchers', '~> 2.0'
